ML/ML/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Openml.urls')),
]

ML/Openml/urls.py
from django.contrib import admin
from django.urls import path,include
from Openml import views

app_name = "Openml"


urlpatterns = [  
    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('upload/csv/', views.upload_csv, name='upload_csv'),
    path('xy/',views.xy),
    path('missing_values/',views.missing_values),
    path('train_test/',views.train_test),
    path('slr/',views.slr),
    path('Feature_Scaling/',views.Feature_Scaling),
    path('prediction/',views.prediction),
    path('categorical_data/',views.categorical_data),
    path('visual_traindata/',views.visual_traindata),
    path('visual_testdata/',views.visual_testdata),
    path('train_model/',views.train_model,name='train_model'),
]

ML/Openml/models.py
from django.db import models
from django import forms
from django.forms import ModelForm


# Create your models here.  
class Member(models.Model):
    firstname=models.CharField(max_length=30)
    lastname=models.CharField(max_length=30)
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=12)
 
    def __str__(self):
        return self.firstname + " " + self.lastname
  
  
    class Meta:  
        db_table = "web_member"

class Csv(forms.Form):
	title = forms.CharField(max_length=50)
	myfile = forms.FileField()

class Values(models.Model):
    x_value=models.CharField(max_length=7)
    y_value=models.CharField(max_length=7)

ML/Openml/views.py
from django.shortcuts import render, redirect
from Openml.models import Member, Csv, Values 
from django.core.files.storage import FileSystemStorage 
import pdb
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

def index(request):
    if request.method == 'POST':
        if Member.objects.filter(username=request.POST['username'], password=request.POST['password']).exists():
            context = {'sm':'username already exists give another one'}
            return render(request,'index.html',context)
        else:   
            member = Member(username=request.POST['username'], password=request.POST['password'],  firstname=request.POST['firstname'], lastname=request.POST['lastname'])
            member.save()
            return redirect('login/')
    else:
        return render(request, 'index.html')
 
def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        if Member.objects.filter(username=request.POST['username'], password=request.POST['password']).exists():
            #member = Member.objects.get(username=request.POST['username'], password=request.POST['password'])
            pdb.set_trace()
            return redirect('/upload/csv')  
        else:
            context = {'msg': 'Invalid username or password'}
            return render(request, 'login.html', context)  

def handle_uploaded_file(f):
    with open('/home/gups/workingdir/ML_using_Django/ML/Openml/uploaded_file/save.csv', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)       
            
def upload_csv(request):
    if request.method=='POST':
        form = Csv(request.POST,request.FILES)
        f= request.FILES['filename']  
        handle_uploaded_file(f)   
        reading_csv(f)
        context={'msg':'upload done'}           
        return render(request, 'upload_csv.html',context)
    else:
        return render(request, 'upload_csv.html')

dataset = None
def reading_csv(f):
    global dataset
    dataset = pd.read_csv('/home/gups/workingdir/ML_using_Django/ML/Openml/uploaded_file/save.csv')
    

         
def xy(request):
    if request.method == 'GET':
        x = request.GET.get('x')
        y = request.GET.get('y')
        x=int(x)
        y=int(y)
        create_matrix(x,y)        
    context = {'x': x, 'y': y}
    return render(request,'upload_csv.html', context)


def create_matrix(x,y):
    global dataset,X,Y,bx
    if x == 1:
        x=1
    else:
        x=x-1

    y=y-1
    bx=x
    X=dataset.iloc[:,:x].values
    pdb.set_trace()
    Y=dataset.iloc[:,y:].values

def missing_values(request):
    global X
    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    imputer.fit(X[:,:])
    X[:,:] = imputer.transform(X[:,:])
    context = {'mv' : 'Done'}
    return render(request,'upload_csv.html',context)

    
def train_test(request):
    global X,Y,X_train, X_test, y_train, y_test
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 1/3, random_state = 0)
    context = {'tt':'Train and test data got Created'}
    return render(request,'upload_csv.html',context)

def slr(request):
    global X_train,y_train,regressor
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(X_train, y_train)
    context = {'slr':'Model prepared for test'}
    return render(request,'train_model.html',context)

def prediction(request):
    global X_test,y_pred,regressor
    y_pred = regressor.predict(X_test)    
    context = {'y_pred': y_pred}
    return render(request,'train_model.html',context)    

def visual_traindata(request):
    global X_train,y_train,regressor
    plt.scatter(X_train, y_train, color = 'red')
    plt.plot(X_train, regressor.predict(X_train), color = 'blue')
    plt.title('Salary vs Experience (Training set)')
    plt.xlabel('Years of Experience')
    plt.ylabel('Salary')
    plt.savefig('Train.png', dpi=200)
    image_data = open("/home/gups/workingdir/ML_using_Django/ML/Train.png", "rb").read()
    return HttpResponse(image_data, content_type="image/png")

def visual_testdata(request):
    global X_train,y_train,regressor,X_test, y_test
    plt.scatter(X_test, y_test, color = 'red')
    plt.plot(X_train, regressor.predict(X_train), color = 'blue')
    plt.title('Salary vs Experience (Test set)')
    plt.xlabel('Years of Experience')
    plt.ylabel('Salary')
    plt.savefig('Test.png', dpi=220)
    image_data = open("/home/gups/workingdir/ML_using_Django/ML/Test.png", "rb").read()
    return HttpResponse(image_data, content_type="image/png")

def train_model(request):
    return render(request,'train_model.html')

def categorical_data(request):
    global X,dataset,colname,x1,xn
    if request.method == 'GET':
        a = request.GET.get('a')
        qn = int(a)
        qn = qn-2
        colname = dataset.columns[qn]
        x1=dataset[colname]
        xn=x1.nunique()
        ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [qn])], remainder='passthrough')
        pdb.set_trace()
        X = np.array(ct.fit_transform(X))
        pdb.set_trace()
    context = {'a': a}
    return render(request,'upload_csv.html', context)

def Feature_Scaling(request):
    global X_train,X_test,xn
    if request.method == 'GET':
        m = request.GET.get('m')
        n = request.GET.get('n')
        m=int(m)
        n1=int(n)
        m=(m+xn)-3
        n1=(n1+xn-2)+1
        pdb.set_trace()
        sc = StandardScaler()
        X_train[:,m:n1] = sc.fit_transform(X_train[:,m:n1])
        pdb.set_trace()
        X_test[:,m:n1] = sc.transform(X_test[:,m:n1]) 
    context={'msg' : 'Done'}
    return render(request,'train_model.html')

ML/Openml/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Openml</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">OpenMl</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

ML/Openml/templates/home.html
<h1>Home</h1>

ML/Openml/templates/index.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="col-md-2">
        <a href="/login">Login</a>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control" required="required">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" required="required"/>
        </div>
        <div class="form-group">
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" class="form-control" required="required"/>
        </div>
        <div class="form-group">
            <label for="lastname">Lastname</label>
            <input type="text" name="lastname" class="form-control" required="required"/>
        </div>
        <br />
        <div class="form-group">
            <button type="submit" class="btn btn-primary form-control"><span class="glyphicon glyphicon-save"></span> Submit</button>
        </div>
        {{sm}}
    </div>
</form>
{% endblock %}

ML/Openml/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" class="post-form" action="/login/">  
    {% csrf_token %}
    <div class="col-md-2">
         <a href="/">Signup</a>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control" required="required"/>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" required="required"/>
        </div>
        <center><label class="text-danger">{{ msg }}</label></center>
        <br />
        <div class="form-group">
            <button class="btn btn-primary form-control"><span class="glyphicon glyphicon-log-in"></span> Login</button>
        </div>
    </div>
</form> 
{% endblock %}

ML/Openml/templates/train_model.html
{% extends 'base.html' %}
{% block content %}
<form action="/slr/" method='GET'>
  <label for="name">1.Simple linear Regression</label>
  <input type="submit">
  {{slr}}
</form>

<form action="/prediction/" method='GET'>
  <label for="name">3.Prediction</label>
  <input type="submit">
  {{y_pred}}
</form>


<form action="/visual_testdata/" method='GET'>
  <label for="name">4.Visualising the Test set results</label>
  <input type="submit">
</form>

<form action="/visual_traindata/" method='GET'>
  <label for="name">5.Visualising the Training set results</label>
  <input type="submit">
</form>
{% endblock %}

ML/Openml/templates/upload_csv.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url "Openml:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
{% csrf_token %}
<div class="form-group">
    <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">1.UploadFile: </label>
    <div class="col-md-8">
        <input type="file" name="filename">
    </div>                    
</div>
<div class="form-group">                    
    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
    </div> 
    {{msg}}
</div>
</form>


<form action="/xy/" method="GET">  
  <label for="name">2.Matrix:</label>
  <div>
    <div>
    <label for="x">X = </label>
    <input type="number" name="x" id="x" value="{{x}}">
    </div>
    <div>
    <label for="y">Y = </label>
    <input type="number" name="y" id="y" value="{{y}}">
    </div>
    <input type="submit">
  </div>
</form>

<form action="/categorical_data/" method="GET">
  <label for="categorical_data">3.Which coloumn you want to transform:</label>
  <input type="number" name="a" id="a" value="{{a}}">
  <input type="submit">
</form>

<form action="/missing_values/" method='GET'>
  <label for="name">4.missing_values</label>
  <input type="submit">
  {{mv}}
</form>

<form action="/train_test/" method='GET'>
  <label for="name">5.Train and Test data</label>
  <input type="submit">
  {{tt}}
</form>

<form action="/Feature_Scaling/" method="GET">  
  <label for="name">6.Feature_Scaling:</label>
  <div>
    <div>
    <label for="m">M = </label>
    <input type="number" name="m" id="m" value="{{m}}">
    </div>
    <div>
    <label for="n">n = </label>
    <input type="number" name="n" id="n" value="{{n}}">
    </div>
    <input type="submit">
  </div>
</form>

{% endblock %}